// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdUgo_WPobakaxd96JHgPQ5RNbkFceKXM',
    appId: '1:527307792238:web:e0871e6fa65cdaf3c02b7f',
    messagingSenderId: '527307792238',
    projectId: 'jaydev-aeec1',
    authDomain: 'jaydev-aeec1.firebaseapp.com',
    storageBucket: 'jaydev-aeec1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpCwmPk1WF5HqYgh-n-uZdIJbfEsHAalk',
    appId: '1:527307792238:android:9202931329f498b0c02b7f',
    messagingSenderId: '527307792238',
    projectId: 'jaydev-aeec1',
    storageBucket: 'jaydev-aeec1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMwZMRvB8vceIarA3s8GlKm6QGD_I4CdU',
    appId: '1:527307792238:ios:6404af2ff8cd629dc02b7f',
    messagingSenderId: '527307792238',
    projectId: 'jaydev-aeec1',
    storageBucket: 'jaydev-aeec1.appspot.com',
    iosBundleId: 'com.example.authj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMwZMRvB8vceIarA3s8GlKm6QGD_I4CdU',
    appId: '1:527307792238:ios:6404af2ff8cd629dc02b7f',
    messagingSenderId: '527307792238',
    projectId: 'jaydev-aeec1',
    storageBucket: 'jaydev-aeec1.appspot.com',
    iosBundleId: 'com.example.authj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdUgo_WPobakaxd96JHgPQ5RNbkFceKXM',
    appId: '1:527307792238:web:4a30b82c230bc193c02b7f',
    messagingSenderId: '527307792238',
    projectId: 'jaydev-aeec1',
    authDomain: 'jaydev-aeec1.firebaseapp.com',
    storageBucket: 'jaydev-aeec1.appspot.com',
  );
}
